spring.application.name=1clickapply
# Base de données PostgreSQL (Localhost)

#spring.datasource.url=jdbc:postgresql://localhost:5432/oneclickapply_db
#spring.datasource.username=oneclick_user
#spring.datasource.password=oneclick_pass
spring.datasource.driver-class-name=org.postgresql.Driver
# Base de donnée Neon (https://neon.com/)
spring.datasource.url=${NEON_DB_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Configuration du serveur
server.port=8080